import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AppContextProvider } from '@/context/appcontext'
import { getCurrentUser } from './actions/getCurrentUser'
import Navbar from '@/components/navbar'
import TrackPlayer from '@/components/trackplayer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider user={currentUser}>
          <Navbar/>
          <TrackPlayer trackId="2D3z17LBMJ2HEHeBFFjTLi"/>
          {children}
        </AppContextProvider>
      </body>
    </html>
  )
}
